name: Unzip GAMERZ ADDA

on:
  push:
    paths:
      - 'GAMERZ ADDA.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip archive
        run: |
          unzip -o "GAMERZ ADDA.zip" -d extracted_project
          rsync -a extracted_project/ . --exclude .git --delete
      - name: Commit extracted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Unzip GAMERZ ADDA.zip via workflow" || echo "No changes to commit"
          git push || echo "Push failed"
